Ignores additional properties by default
flipstone/json-fleece pull request #29
Opened 2024-04-09 16:54 UTC by AugmenTab

This adds a config field `ignoreAdditionalProperties` which is defaulted to `True`. When code gen encounters `additionalProperties: false`, we now ignore it or produce an error based on the value of that config field.

2024-04-09 17:19 UTC, jbrechtel approved these changes

2024-04-09 18:07 UTC, qxjit requested changes

2024-04-09 18:07 UTC, qxjit commented on json-fleece-codegen-util/codegen-prelude.dhall
> +    , ignoreAdditionalProperties = True
I think the config name is misleading, and also it should not default to `True`. The default behavior for fleece should not be a setting that doesn't following the OpenAPI spec

2024-04-09 18:07 UTC, qxjit commented on json-fleece-openapi3/examples/test-cases/TestCases/Types/MixedInAdditionalPropertiesFalse.hs
> +  , additionalProperties :: (Map.Map T.Text FC.AnyJSON)
We should not generate code to process additional properties for an item that has `additionalProperties: false`

2024-04-10 14:19 UTC, AugmenTab commented on json-fleece-codegen-util/codegen-prelude.dhall
> +    , ignoreAdditionalProperties = True
The name was changed to `strictAdditionalProperties` in [`0b7d610`](https://github.com/flipstone/json-fleece/pull/29/commits/0b7d61058ee02c822103171eb264242c0737a342).

2024-04-10 14:19 UTC, AugmenTab commented on json-fleece-openapi3/examples/test-cases/TestCases/Types/MixedInAdditionalPropertiesFalse.hs
> +  , additionalProperties :: (Map.Map T.Text FC.AnyJSON)
This was fixed in [`0b7d610`](https://github.com/flipstone/json-fleece/pull/29/commits/0b7d61058ee02c822103171eb264242c0737a342).

2024-04-10 18:50 UTC, qxjit approved these changes

2024-04-10 18:52 UTC, merged